### PR TITLE
Move to kt

### PR DESCRIPTION
**Pull request by parshav**
Auto-converted to Kotlin, then manually re-formatted code.
Added some more tests for EncrpytionK.
TODO: Easier encrpytion for kotlin (lamdas, extensions), separate module for kt.

If you guys think this is worth it, I'd be down to put in some more time to complete some of those tasks. Nice library.

### CODE REVIEW

**Comment by parshav** [comment]
Can someone elaborate possible on why it failed? Thanks !

**Comment by ademar111190** [comment]
Hi @parshav thank you for your contribution.
I'm a kotlin addict, but I have doubts if this project should use kotlin.
I have to add the bitrise yaml file to the project to help contributors like you to test, for now let me share with you the yaml file:
```
---
format_version: '3'
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
project_type: android
trigger_map:
- push_branch: "*"
  workflow: primary
- pull_request_source_branch: "*"
  workflow: primary
workflows:
  deploy:
    steps:
    - activate-ssh-key@3.1.1:
        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
    - git-clone@3.5.0: {}
    - cache-pull@1.0.0: {}
    - script@1.1.4:
        title: Do anything with Script step
    - install-missing-android-tools@1.0.3: {}
    - gradle-runner@1.7.1:
        inputs:
        - gradle_file: "$GRADLE_BUILD_FILE_PATH"
        - gradle_task: assembleRelease
        - gradlew_path: "$GRADLEW_PATH"
    - deploy-to-bitrise-io@1.3.5: {}
    - cache-push@1.1.1: {}
  primary:
    steps:
    - activate-ssh-key@3.1.1:
        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
    - git-clone@3.5.0: {}
    - gradle-unit-test@1.0.1:
        inputs:
        - gradle_file: Encryption/build.gradle
        - gradlew_file_path: Encryption/gradlew
        - unit_test_flags: 
    - gradle-unit-test@1.0.1:
        inputs:
        - gradle_file: Examples/Java/build.gradle
        - gradlew_file_path: Examples/Java/gradlew
        - unit_test_flags: 
    - gradle-unit-test@1.0.1:
        inputs:
        - gradle_file: Examples/Kotlin/build.gradle
        - gradlew_file_path: Examples/Kotlin/gradlew
        - unit_test_flags: 
    - gradle-unit-test@1.0.1:
        inputs:
        - gradle_file: Examples/Android/build.gradle
        - gradlew_file_path: Examples/Android/gradlew
        - unit_test_flags: 
```
and I'm attaching the build fail log to help you understand why it is broken.
Best.
[4b9516df5a48a287.log](https://github.com/simbiose/Encryption/files/2586730/4b9516df5a48a287.log)

**Comment by parshav** [comment]
Thanks for the info @ademar111190 , if I may ask, why don't you think it should move over to kotlin? What about having separate modules for each?

**Comment by ademar111190** [comment]
Hi @parshav sorry for the long time to answer.
The reason is that I don't see why to move to kotlin, as I said I'm an addict of kotlin, and I advocate for large projects to move to kotlin, but this small library, I don't see the benefits.

**Pull request closed without merging**
